/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    EditorChartTypePicker: typeof import('./src/components/Editor/EditorChartTypePicker.vue')['default']
    EditorDataInput: typeof import('./src/components/Editor/EditorDataInput.vue')['default']
    EditorPanel: typeof import('./src/components/Editor/EditorPanel.vue')['default']
    EditorPropertyForm: typeof import('./src/components/Editor/EditorPropertyForm.vue')['default']
    ExportPanel: typeof import('./src/components/Export/ExportPanel.vue')['default']
    LayoutShell: typeof import('./src/components/Layout/LayoutShell.vue')['default']
    LayoutSidebar: typeof import('./src/components/Layout/LayoutSidebar.vue')['default']
    PreviewChart: typeof import('./src/components/Preview/PreviewChart.vue')['default']
    PreviewPanel: typeof import('./src/components/Preview/PreviewPanel.vue')['default']
  }
}
