// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,chart:10, data:16, highlight:36, areafill:40, range:44, note:48, annotation:52, series:56, step:60, transform:66}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*zOYQPOOQOQPOOO_QPO'#C_OdQPO,58yO!^QPO1G.eOOQO'#Cg'#CgO!eQPO'#CfOOQO'#Cb'#CbOOQO'#DO'#DOO!jQPO7+$PO!qQPO'#CcO!vQPO'#CmO!{QPO'#CoO#QQPO'#CqO#VQPO'#CsO#[QPO'#CuO#aQPO'#CwO#fQPO'#CyO#kQPO'#C|OOQO7+$P7+$PO#pQPO,59QOOQO-E6|-E6|OOQO<<Gk<<GkO$OQPO,58}O$ZQPO,59XO$`QPO,59ZO$eQPO,59]O$pQPO,59_O${QPO,59aO%QQPO,59cO%VQPO,59eO%[QPO,59hOOQO'#Cj'#CjOOQO1G.l1G.lOOQO'#Ce'#CeOOQO'#DP'#DPO%aQPO1G.iOOQO1G.i1G.iO%lQPO1G.sO%wQPO1G.uOOQO'#DQ'#DQO%|QPO1G.wOOQO1G.w1G.wO&XQPO1G.yOOQO1G.y1G.yO&dQPO1G.{O&oQPO1G.}O'fQPO1G/PO'mQPO1G/SOOQO-E6}-E6}OOQO7+$T7+$TO'xQPO7+$_OOQO7+$_7+$_O(TQPO7+$aOOQO-E7O-E7OOOQO7+$c7+$cOOQO7+$e7+$eO(`QPO7+$gOOQO7+$g7+$gO(kQPO7+$iOOQO7+$i7+$iOOQO'#C{'#C{OOQO'#DR'#DRO(vQPO7+$kOOQO7+$k7+$kO(}QPO7+$nOOQO7+$n7+$nOOQO<<Gy<<GyO)YQPO<<G{OOQO<<G{<<G{OOQO<<HR<<HROOQO<<HT<<HTOOQO-E7P-E7POOQO<<HV<<HVOOQO<<HY<<HYOOQOAN=gAN=g",
  stateData: ")k~OxOSPOS~OTQO~OSRO~OySO~OSTOWYO[TObZOd[Of]Oh^Oj_Ol`OnaOqbO~OzcO~PiO]dO~OzfO~PiOygO~O[hO~O[iO~OyjO~OykO~O[lO~O[mO~O[nO~OSoO~OSpO[pO_pO`pO~OSTO[TOzuO~OyvO~O[wO~OSTO[TOzzO~OSTO[TOz|O~Oy}O~Oy!OO~Oy!PO~Oy!QO~OSTO[TOz!SO~OSTO[TOz!UO~Oy!VO~OSTO[TOz!XO~OSTO[TOz!YO~OSTO[TOz![O~OSTO[TOz!^O~OSTOWYO[TObZOd[Of]Oh^Oj_O~Oz!bO~P&zOSTO[TOz!dO~OSTO[TOz!eO~OSTO[TOz!gO~OSTO[TOz!hO~OSTO[TOz!iO~Oz!kO~P&zOSTO[TOz!lO~OSTO[TOz!mO~O_`PSP~",
  goto: "$mvPPPwPPz!OP!W![!xPP#`PP!OP!OP!OP!OP!OP#cP#cP#g#cP#k#q#w$gRPOTWSXSVSXT!_!P!aTsgtSVSXSrgtlxjkvy{}!O!Q!T!V!Z!]!c!fT!_!P!ayUSXgjktvy{}!O!P!Q!T!V!Z!]!a!c!fRqdTVSXT!`!P!aQXSReXQtgR!RtQyjQ{kQ!Tv^!Wy{!T!Z!]!c!fQ!Z}Q!]!OQ!c!QR!f!VQ!a!PR!j!a",
  nodeNames: "⚠ LineComment Chart ChartDecl Identifier chart ChartMember DataBlock data DataEntry Property PropertyKey String Equals PropertyValue Percentage Number Highlight highlight AreaFill areafill RangeAnnotation range NoteAnnotation note Annotation annotation Series series Step step StepMember Transform transform",
  maxTerm: 42,
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "'T~ReX^!dpq!drs#Xst$r}!O%Z!P!Q&V!Q![%a!_!`&t!c!}$r#R#S$r#T#o$r#o#p&y#q#r'O#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~!iYx~X^!dpq!d#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~#[VOr#Xrs#qs#O#X#O#P#v#P;'S#X;'S;=`$l<%lO#X~#vO[~~#yZOr#Xrs#Xs#O#X#O#P#X#P#b#X#b#c#X#c#h#X#h#i#X#i;'S#X;'S;=`$l<%lO#X~$oP;=`<%l#X~$wUS~st$r}!O$r!Q![$r!c!}$r#R#S$r#T#o$r~%^P!Q![%a~%fR`~uv%o!O!P%t!Q![%a~%tO_~~%wP!Q![%z~&PQ`~uv%o!Q![%z~&YP!P!Q&]~&bSP~OY&]Z;'S&];'S;=`&n<%lO&]~&qP;=`<%l&]~&yO]~~'OOy~~'TOz~",
  tokenizers: [0],
  topRules: {"Chart":[0,2]},
  specialized: [{term: 4, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 389
})
