import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { join, basename } from 'node:path'
import { existsSync } from 'node:fs'
import matter from 'gray-matter'

const SRC = join(import.meta.dirname, '..', 'src')
const PUBLIC = join(SRC, 'public')
const SITE = 'https://docs.blueprintchart.com'

const HEADER = `# Blueprint Chart — full documentation

> The open chart format an LLM writes and the browser renders. Author charts as a compact plain-text \`.bpc\` DSL that any browser renders to interactive, accessible SVG. Static-first: no backend, no account, data stays in the browser.

This file concatenates the Blueprint Chart documentation for ingestion by LLMs and AI agents. A curated link index is at ${SITE}/llms.txt. Generated by scripts/build-llms-full.ts — do not edit by hand.
`

// Ordered sections. Within each group, files in `order` come first (in this
// order); any other .md files present are appended alphabetically and logged,
// so new pages are never silently dropped.
const SECTIONS: { group: string, title: string, order: string[] }[] = [
  { group: 'guide', title: 'Guide', order: ['getting-started', 'mcp', 'dsl-editor', 'scenes', 'data-transforms', 'embed', 'palettes', 'accessibility'] },
  { group: 'reference/dsl', title: 'DSL reference', order: ['index', 'properties', 'annotations', 'scenes-and-transforms'] },
  { group: 'reference/api', title: 'API reference', order: ['index'] },
  { group: 'charts', title: 'Chart types', order: ['index', 'line', 'line-multi', 'area', 'area-stacked', 'bar-vertical', 'bar-horizontal', 'bar-multi', 'bar-grouped', 'bar-stacked', 'bar-split', 'column-stacked', 'pie', 'donut'] },
  { group: 'handbook', title: 'Handbook', order: ['index', 'choosing', 'color', 'accessibility', 'annotations', 'labels', 'axes', 'tooltips', 'typography', 'anti-patterns', 'design-principles', 'frame-elements'] },
]

function urlFor(group: string, slug: string): string {
  return slug === 'index' ? `${SITE}/${group}/` : `${SITE}/${group}/${slug}`
}

async function main() {
  const parts: string[] = [HEADER]

  for (const section of SECTIONS) {
    const dir = join(SRC, section.group)
    if (!existsSync(dir)) {
      console.warn(`skip missing group: ${section.group}`)
      continue
    }
    const present = (await readdir(dir)).filter(f => f.endsWith('.md')).map(f => basename(f, '.md'))
    const ordered = section.order.filter(s => present.includes(s))
    const extra = present.filter(s => !section.order.includes(s)).sort()
    if (extra.length) {
      console.warn(`${section.group}: appending unlisted pages -> ${extra.join(', ')}`)
    }

    parts.push(`\n\n${'='.repeat(72)}\n# ${section.title}\n${'='.repeat(72)}`)
    for (const slug of [...ordered, ...extra]) {
      const raw = await readFile(join(dir, `${slug}.md`), 'utf8')
      const content = matter(raw).content.trim()
      parts.push(`\n\n## Source: ${urlFor(section.group, slug)}\n\n${content}`)
    }
  }

  if (!existsSync(PUBLIC)) {
    await mkdir(PUBLIC, { recursive: true })
  }
  const out = join(PUBLIC, 'llms-full.txt')
  await writeFile(out, parts.join('\n') + '\n')
  const bytes = (await readFile(out)).length
  console.log(`Wrote ${out} (${(bytes / 1024).toFixed(1)} KB)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
